print("Hello World")
print("How Are You?")
print("Virat Singh")
print("I Am Very Intelligent Person ")
print("My father Name Is Mr Rajesh Singh Tomar ")
print("My Mother Name Is Mrs Ranno Singh Tomar ")
print("I Am Basically From Kanpur Uttar Pradesh ")
print("My Strenghth Are I Am Self Motivated Hardworking And a supportive Guy ")
print ("My Weakness Are I am Egoistic Arrogant And Poor In Handling Emotions ")
print ("This Is All About Me ")